Neos:
  Neos:
    fusion:
      autoInclude:
        GeosphereWeb.Bootstrap43: true
    nodeTypes:
      groups:
        GeosphereWeb.Bootstrap43:
          position: 300
          label: 'GeosphereWeb:Bootstrap4.3'
          collapsed: false
#    userInterface:
#      scrambleTranslatedLabels: true