Neos:
  Neos:
    fusion:
      autoInclude:
        'GeosphereWeb.Bootstrap43': true
    nodeTypes:
      groups:
        'GeosphereWeb.Bootstrap43':
          position: 300
          label: 'GeosphereWeb : Bootstrap4.3'
          collapsed: false
    userInterface:
      editPreviewModes:
        print:
          isEditingMode: false
          isPreviewMode: true
          fusionRenderingPath: print
          title: 'GeosphereWeb.Bootstrap43:Main:editPreviewModes.print'
          position: 200
      translation:
        autoInclude:
          GeosphereWeb.Bootstrap43:
            - Main
            - 'NodeTypes/*'
#  ContentRepository:
#    contentDimensions:
#      language:
#        label: 'GeosphereWeb.Bootstrap43:Main:contentDimensions.language'
#        icon: icon-language
#        default: de
#        defaultPreset: de
#        presets:
#          de:
#            label: 'German'
#            values:
#              - de
#              - en_UK
#            uriSegment: de
#          en_US:
#            label: 'English (US)'
#            values:
#              - en_US
#            uriSegment: en
#          en_UK:
#            label: 'English (UK)'
#            values:
#              - en_UK
#              - en_US
#            uriSegment: uk
